let name = "pranav";
let school = "Masai";
let grade = "A++";
let section = "A";
let roll_no = 4;
let english = 94;
let maths = 99;
let science = 97;
console.log("Name"+"   :- "+name);
console.log("School"+"  :-  "+school);
console.log("Grade"+"  :-  "+grade);
console.log("Section"+"  :-  "+section);
console.log("Roll_no"+"  :-  "+roll_no);
console.log("English"+"  :-  "+english);
console.log("Maths"+"  :-  "+maths);
console.log("Science"+"  :-  "+science);